lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # 1 hour
    user_id_claim: email # This field will be used to identify the user
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization 