services:
  # FastAPI application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://peso_user:peso_password@db:5432/peso_db
      - SECRET_KEY=your-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - FROM_EMAIL=your-email@gmail.com
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - peso-network
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=peso_db
      - POSTGRES_USER=peso_user
      - POSTGRES_PASSWORD=peso_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - peso-network
    restart: unless-stopped

  # Database migrations
  migrations:
    build: .
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://peso_user:peso_password@db:5432/peso_db
    depends_on:
      - db
    networks:
      - peso-network

volumes:
  postgres_data:

networks:
  peso-network:
    driver: bridge 